### ISSUE TITLE
Assignment 3 is ready for grading!

### ISSUE THREAD

**Issue by ryan6351** [VIS-2129-F2020/rjohnson-vis#3]
Thank you so much for the class-wide extension - it was really helpful to be able to devote some extra time to studio, and it means a lot knowing that we have a professor as considerate as you!

As for the matter at hand, here is a link to Assignment 3: https://vis-2129-f2020.github.io/rjohnson-vis/Assignment3VIS.html

Thanks!

**Comment by bauranov** [comment]
Visually stunning plots. I knew Austin was gerrymandered, but this is beyond crazy (enter look-how-they-massacred-my-boy meme). 

I have nothing to add re code. Keep up the great work, looking forward to your next assignment!

EDIT: I noticed the scales are in miles whereas areas and distances are in kilometers. Change unit_category to metric.

**Comment by ryan6351** [comment]
> Visually stunning plots. I knew Austin was gerrymandered, but this is beyond crazy (enter look-how-they-massacred-my-boy meme).
> 
> I have nothing to add re code. Keep up the great work, looking forward to your next assignment!
> 
> EDIT: I noticed the scales are in miles whereas areas and distances are in kilometers. Change unit_category to metric.

Thanks for the feedback! I thought that the function I used to convert the scale to miles actually scaled it properly (not just changing the label), but I may be wrong on that. 

And yes, Austin is, although the city council boundaries are actually quite fair - a lot of the weirdness comes from physical elements (in many places the city limit follows the river/lakes in the area) and from weird annexation policies which have absorbed many "islands" of area into the full-purpose jurisdiction, with just a strip of road or land area connecting the boundaries.
